### ISSUE TITLE
偶尔报错

### ISSUE THREAD

**Issue by qq570026938** [devin1014/DLNA-Cast#11]
java.lang.ExceptionInInitializerError
        at org.fourthline.cling.transport.impl.AsyncServletStreamServerImpl.createServlet(AsyncServletStreamServerImpl.java:98)
        at org.fourthline.cling.transport.impl.AsyncServletStreamServerImpl.init(AsyncServletStreamServerImpl.java:76)
        at org.fourthline.cling.transport.RouterImpl.startAddressBasedTransports(RouterImpl.java:434)
        at org.fourthline.cling.transport.RouterImpl.enable(RouterImpl.java:132)
        at org.fourthline.cling.android.AndroidRouter.enable(AndroidRouter.java:91)
        at org.fourthline.cling.UpnpServiceImpl.<init>(UpnpServiceImpl.java:87)
        at org.fourthline.cling.android.AndroidUpnpServiceImpl$1.<init>(AndroidUpnpServiceImpl.java:54)
        at org.fourthline.cling.android.AndroidUpnpServiceImpl.onCreate(AndroidUpnpServiceImpl.java:54)
        at com.android.cast.dlna.dmc.DLNACastService.onCreate(DLNACastService.java:22)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3967)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2092)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)

**Comment by yzhg-ux** [comment]
有解决是什么问题吗？
